# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_opinion',
        ),
        migrations.AddField(
            model_name='opinion',
            name='case_opinion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lawdb.Case'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='opinion_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_below_cite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_below_cite', to='lawdb.Opinion'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_court_below',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lawdb.Court'),
        ),
        migrations.AlterField(
            model_name='court',
            name='lower_court',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inferior_court', to='lawdb.Court'),
        ),
        migrations.AlterField(
            model_name='court',
            name='upper_court',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superior_court', to='lawdb.Court'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='for_defendant',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='for_plantiff',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='opinion_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
