# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0002_auto_20160822_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_plantiff', models.PositiveSmallIntegerField(default=0)),
                ('for_defendant', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'CaseCite',
            },
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite_name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Cite',
            },
        ),
        migrations.RemoveField(
            model_name='case',
            name='citations',
        ),
        migrations.AddField(
            model_name='case',
            name='case_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_below_cite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lawdb.Cite'),
        ),
        migrations.AddField(
            model_name='casecite',
            name='case_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawdb.Case'),
        ),
        migrations.AddField(
            model_name='casecite',
            name='cite_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawdb.Cite'),
        ),
    ]
