# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0003_auto_20160823_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='lower_court',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inferior_court', to='lawdb.Court'),
        ),
        migrations.AlterField(
            model_name='court',
            name='upper_court',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superior_court', to='lawdb.Court'),
        ),
    ]
