# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0005_auto_20160901_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='law_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawdb.LawSchool'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='state_born',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='judge',
            name='year_born',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
