# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0007_auto_20160901_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='judge',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='judge',
            unique_together=set([('first_name', 'last_name', 'state_born')]),
        ),
    ]
