# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0008_auto_20160902_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='publication',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='syllabus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='ruling_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='argue_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date argued'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_below_cite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lawdb.Cite'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_court_below',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lawdb.Court'),
        ),
        migrations.AlterField(
            model_name='case',
            name='decide_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date decided'),
        ),
        migrations.AlterField(
            model_name='case',
            name='defendant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='docket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='plantiff',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
