# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0009_auto_20160907_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='defendant',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='plantiff',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
