# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0010_auto_20160908_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='docket',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
