# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0011_auto_20160908_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='topic',
            field=models.CharField(max_length=60),
        ),
    ]
