# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0013_auto_20160911_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='fed_or_state',
            field=models.CharField(choices=[('Fed', 'Federal'), ('State', 'State')], max_length=7),
        ),
        migrations.AlterField(
            model_name='code',
            name='section',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawdb.State'),
        ),
        migrations.AlterField(
            model_name='code',
            name='subtitle',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
