# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0014_auto_20160919_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='chapter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='section',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='subtitle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='topic',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='url',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
