# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0015_auto_20160919_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawdb.Case')),
            ],
            options={
                'db_table': 'CaseCode',
            },
        ),
        migrations.AlterField(
            model_name='code',
            name='section',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casecode',
            name='code_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawdb.Code'),
        ),
    ]
