# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0017_auto_20160925_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
