# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0018_auto_20160925_2049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='code',
            unique_together=set([('title', 'code_name', 'chapter', 'section')]),
        ),
    ]
