# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawdb', '0019_auto_20160925_2125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='case',
            unique_together=set([('case_name', 'topic')]),
        ),
        migrations.AlterUniqueTogether(
            name='casecode',
            unique_together=set([('code_link', 'case_link')]),
        ),
    ]
